[package]
name = "logr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.30.0"
regex = "1.12.2"
tokio = { version = "1.49.0", features = ["full"] }
